Sonarbranch sonar corrections review
kovacsge11/ivt-lab pull request #3
Opened 2018-05-04 07:30 UTC by kovacsge11

Review my code corrections caused by sonar

2018-05-04 07:49 UTC, dorob requested changes
1 change need, but great

2018-05-04 07:49 UTC, dorob commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +  private double failureRate = 0.0;
ok

2018-05-04 07:49 UTC, dorob commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +    if (r >= failureRate) {
ok

2018-05-04 07:49 UTC, dorob commented on src/main/java/hu/bme/mit/spaceship/GT4500.java
> +	if (allCondition) {
good, better readability

2018-05-04 07:49 UTC, dorob commented on src/main/java/hu/bme/mit/spaceship/GT4500.java
> +          if (secondaryTorpNotEmpty) {
good, simpler than the other

2018-05-04 07:49 UTC, dorob commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> -    if (r >= FAILURE_RATE) {
In 22 and 24 row FAILURE_RATE name still exists

2018-05-04 17:18 UTC, kovacsge11 commented
Corrected all bugs.

2018-05-04 17:19 UTC, merged

2018-05-05 11:34 UTC, dorob reviewed
everything is ok

2018-05-05 11:34 UTC, dorob commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +        failureRate = 0.0;
ok, good